server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/aml?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 111111
  jpa:
    show-sql: false
logging:
  file: aml.log
appCfg:
  shIp: 172.18.160.50
  sshPort: 22
  sshUser: hdrisk
  sshPwd: zaq@1808
  upload: /home/ubuntu
  download: //172.18.164.148:8080/download/
